### ISSUE TITLE
Noon shows up as "0PM", but should be "12PM"

### ISSUE THREAD

**Issue by gkd720** [tejainece/date_format#1]
I'm formatting a DateTime object that shows up in Linux as 'Mon Nov  5 12:00:00 EST 2018'. In my app, I'm formatting it with '[h,am]', and it outputs "0PM", when I would expect '12PM'. In the code, I see writing AM or PM based on: date.hour date.hour < 12 ? 'AM' : 'PM'. Maybe this should be "<="? Or, should the outputting of the hour not be a plain "hour % 12", but if hour%12==0, then add 12? I suspect this would also fix midnight coming out as "0AM". Thanks.

**Comment by tejainece** [comment]
Will fix it

**Comment by tejainece** [comment]
Fixed by https://github.com/tejainece/date_format/commit/b69ab5910e530f2546a522c9a184fbb06562fc1a.

Tests can be found here: https://github.com/tejainece/date_format/blob/b69ab5910e530f2546a522c9a184fbb06562fc1a/test/date_format_test.dart#L30
