### ISSUE TITLE
How to use Localization support?

### ISSUE THREAD

**Issue by saeedjassani** [tejainece/date_format#10]
Hi,

Thanks for this library. I see in the latest commit which says "Locale/internationailization support".

Can you please tell me how can I use it? I want to use Urdu (ur) Locale.

Thanks,
Saeed

**Comment by tejainece** [comment]
There are lot of supported locales. Urdu is not implemented. Please feel free to add Urudu locale and submit a PR.

Here is an example of a locale: https://github.com/tejainece/date_format/blob/master/lib/src/locale/english.dart
