### ISSUE TITLE
Flutter 1.12.13+hotfix.5   error

### ISSUE THREAD

**Issue by LZQL** [tejainece/date_format#11]
when i upgrade flutter  to  Flutter 1.12.13+hotfix.5 

error: The name 'Locale' is defined in the libraries 'dart:ui' and 'package:date_format/src/locale/locale.dart'. (ambiguous_export at [itest] lib/common/index_all.dart:48)

**Comment by tejainece** [comment]
It is because both packages have `Locale` class. You could hide `Locale` class or use named imports.

In version `2.0.1`, I have renamed `Locale` to `DateLocale`. Upgrade to 2.0.1.
