### ISSUE TITLE
when  import 'package:date_format/date_format.dart  Locale Error

### ISSUE THREAD

**Issue by kangshibiao123** [tejainece/date_format#14]
when  import 'package:date_format/date_format.dart'; In the use of internationalization   Locale unrecognized 
supportedLocales: [
        const Locale('en', 'US'), // English
        const Locale('he', 'IL'), // Hebrew
        // ... other locales the app supports
      ],
Can't speak English Translation software written

**Comment by dannycortesv** [comment]
Locales is also not working for me..

**Comment by tejainece** [comment]
Can you explain more? What is not working?

**Comment by bulletBane** [comment]
I have same issue. In package yo have created locale as abstract class -> Locale of flutter are replaced by package's abstract class Locale and in onther widget like dateTimePicker Locale do not work.

**Comment by tejainece** [comment]
There are two ways to fix this.

1) Hide Locale when you import flutter:

import 'flutter' hide Locale;

2) Import date_format with a name:
import 'date_format' as dateFmt;

PS: the code present is not accurate but just explain the concept.

**Comment by tejainece** [comment]
In version 2.0.1, I have renamed Locale to DateLocale. Upgrade to 2.0.1.

This issue should not occur when/if you upgrade to 2.0.1
