### ISSUE TITLE
about the weekday, we cannot get the day 'Friday' .[version 1.0.8] 

### ISSUE THREAD

**Issue by yangdaxi** [tejainece/date_format#16]
I don't know whether there is something wrong with this package when using such code:
formDate(DateTime(DateTime.now().weekday),[DD])

things like that:
formDate(DateTime(5),[DD]),   the result is  Saturday;
formDate(DateTime(6),[DD]),   the result is  Sunday;
formDate(DateTime(7),[DD]),   the result is  Monday;
and, I tried the argument from 1 to 7, there is no Friday.

**Comment by tejainece** [comment]
Did you figure out why it did not work?

**Comment by yangdaxi** [comment]
I just tried it in another way, like using the code:
formDate(DateTime.now(),[DD])

it works.
