### ISSUE TITLE
format

### ISSUE THREAD

**Issue by Geekoo-Joker** [tejainece/date_format#2]

**Comment by Geekoo-Joker** [comment]
为什么要 [yyyy, '-', mm, '-', dd] 这样写？
‘yyyy-mm-dd’ 这样不是更符合吗

**Comment by tejainece** [comment]
@Geekoo-Joker

Hi! Thanks for the question. Did you manage to fix it? I did not understand what you said.

**Comment by Geekoo-Joker** [comment]
[yyyy, '-', mm, '-', dd] This way of using arrays is strange.
‘yyyy-mm-dd’ is more suitable for using strings.
Such as iOS or other：“【   setDateFormat:@"yyyy-mm-dd HH:mm:ss"】”

**Comment by tejainece** [comment]
@Geekoo-Joker With string representation "yyyy-mm-dd HH:mm:ss", you do not get code completion, have to always look at a table, hard to find errors, etc.

Also this is much faster as there is no parsing of string format needed.
