### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by davidAg9** [tejainece/date_format#20]

**Comment by isorensen** [comment]
Plus one! Any idea when it will be available, @tejainece ?

Thanks for the awesome package.

Dart 2.12 and flutter 2.0.0 are now in stable with the null-safety feature.

Migrating this package to null-safety would help a lot. :)

Here's an official guide from dart doc
https://dart.dev/null-safety/migration-guide

**Comment by tejainece** [comment]
@isorensen i will migrate it and publish it in a day or two.

**Comment by nipunasudha** [comment]
> @isorensen i will migrate it and publish it in a day or two.

So glad to hear! We appreciate your time & effort ❤️

**Comment by tejainece** [comment]
The null safe version of this package is now published to pub as version `2.0.0`. Thanks for your patience and support!
