### ISSUE TITLE
How to convert a timestamp to a fixed time zone time？

### ISSUE THREAD

**Issue by morefreeliang** [tejainece/date_format#22]

**Comment by toKnowMore** [comment]
Same problem

**Comment by XiaoWei3209** [comment]
Same problem

**Comment by tejainece** [comment]
Dart `DateTime` only supports UTC and local timezones. There is a package to keep datetimes in different timezone: https://pub.dev/packages/timezone. The [TZDateTime](https://pub.dev/documentation/timezone/latest/timezone.standalone/TZDateTime-class.html) implements `DateTime` interface, so it should work with `date_format` package. I haven't tried it myself.

Could you please try it and share your findings?

Thanks!
