### ISSUE TITLE
You want FrenchDateLocale : voilà !

### ISSUE THREAD

**Issue by stephane-couget** [tejainece/date_format#28]
there is more than to integrate :

`import 'package:date_format/date_format.dart';

class FrenchDateLocale implements DateLocale {
  const FrenchDateLocale();

  final List<String> monthsShort = const [
    'Jan',
    'Féb',
    'Mar',
    'Avr',
    'Mai',
    'Juin',
    'Juil',
    'Aoû',
    'Sep',
    'Oct',
    'Nov',
    'Déc'
  ];

  final List<String> monthsLong = const [
    'Janvier',
    'Février',
    'Mars',
    'Avril',
    'Mai',
    'Juin',
    'Juillet',
    'Août',
    'Septembre',
    'Octobre',
    'Novembre',
    'Décembre'
  ];

  final List<String> daysShort = const [
    'Lun',
    'Mar',
    'Mer',
    'Jeu',
    'Ven',
    'Sam',
    'Dim'
  ];

  final List<String> daysLong = const [
    'Lundì',
    'Mardì',
    'Mercredì',
    'Jeudi',
    'Vendredi',
    'Samedi',
    'Dimanche'
  ];

//don’t exists in France, we are in 24 hours per day
  @override
  String get am => "AM";

  @override
  String get pm => "PM";
}`

**Comment by tejainece** [comment]
@stephane-couget Thanks for the French locale! If possible, can you submit a PR of it?

**Comment by stephane-couget** [comment]
> @stephane-couget Thanks for the French locale! If possible, can you submit a PR of it?

sorry, i don't know how to do a PR yet
