### ISSUE TITLE
Not show correct time , it add extra 5 minitue to orignail date time 

### ISSUE THREAD

**Issue by sadaqatdev** [tejainece/date_format#36]
e.g 2022-09-30 12:00:00.000 we have date time and we show only time then formateDate with [hh, ":", mm, " ", am] string show 12:09 PM

**Comment by tejainece** [comment]
[mm](https://pub.dev/documentation/date_format/latest/date_format/mm-constant.html) is month. Use [nn](https://pub.dev/documentation/date_format/latest/date_format/nn-constant.html) for minute.
