### ISSUE TITLE
Enhancement:  Any possible of adding relative formatting

### ISSUE THREAD

**Issue by penhorwood** [tejainece/date_format#38]
Not sure how this would work but I need relative formatting with a fall back to normal date formatting.

Example:
Today @ 11:15 AM  which would fall back to 11/23/2022 @ 11:15 AM if that is not today.  Same for yesterday and tomorrow.

**Comment by bsutton** [comment]
I really don't think that is a formatting issue, but rather datetime arithmetic.

**Comment by tejainece** [comment]
You could use
