### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by siloebb** [tejainece/date_format#4]
Didn't find a way to replace the months name. There is any way?

**Comment by tejainece** [comment]
Do you mean month names in other languages?

**Comment by vishnyakov-aleks** [comment]
yes

**Comment by tejainece** [comment]
I will implement it. PRs are also welcome.

**Comment by tejainece** [comment]
Thanks for the feature request. This feature has been implemented in https://github.com/tejainece/date_format/commit/32c9e1f399cf5b127d0635f995b4ba4d8d7cce38.

Please feel free to contribute a locale.
