### ISSUE TITLE
yyyy in date_format_base.dart must be in uppercase

### ISSUE THREAD

**Issue by Tzanou123** [tejainece/date_format#41]
The String yyyy (from line 10 of date_format_base) return "yyyy" but when i call the date i get 10/05/yyyy if i replace it by "YYYY" it is working as expected

**Comment by tejainece** [comment]
`print(formatDate(DateTime(1989, 2, 21), [dd, '/', mm, '/', yyyy]));` correctly prints `21/02/1989`.

Please feel free to reopen the issue with more information.
