### ISSUE TITLE
Supporting diffrent languages form months and days names

### ISSUE THREAD

**Issue by ahmadkhedr** [tejainece/date_format#6]
Does this plugin support German and Arabic names for different days and months?

**Comment by tejainece** [comment]
I will work on it over weekend.

PRs are welcome too.

**Comment by ahmadkhedr** [comment]
Any updates?

**Comment by tejainece** [comment]
Thanks for the feature request. This feature has been implemented in https://github.com/tejainece/date_format/commit/32c9e1f399cf5b127d0635f995b4ba4d8d7cce38.

Please feel free to contribute a locale.
